steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/firestore-adapter/firestore-adapter', '.']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/firestore-adapter/firestore-adapter']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - firestore-adapter
      - --image
      - europe-west1-docker.pkg.dev/$PROJECT_ID/firestore-adapter/firestore-adapter
      - --region
      - europe-west1
      - --platform
      - managed
      - --allow-unauthenticated
      - --service-account
      - rhea-app-sa@$PROJECT_ID.iam.gserviceaccount.com
      - --port
      - '8080'

  # Step 4: Wait for deployment to stabilize
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Waiting for service to stabilize..."
        sleep 30

  # Step 5: Sanity check
  - name: 'curlimages/curl'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Running sanity check..."
        curl -sSf "https://firestore-adapter-317624663818.europe-west1.run.app/health" || exit 1

# Options List

options:
  logging: CLOUD_LOGGING_ONLY

# Substitutions
substitutions:
  _REGION: europe-west1
